repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix, --extend-fixable, "F401", --ignore, "D100,W505" ]
    # Run the formatter.
    - id: ruff-format

# "src/**/__init__.py" = ["F401"]
