help:
    just -l -u

clean:
    rm -rf dev-workspace/__pycache__ dev-workspace/results
    find dev-workspace -mindepth 1 -not -name data.csv -exec rm -f {} +

run:
    uv run run.py

test:
    cd dev-workspace && uv run analysis.py
