name: Docs PR Preview

on:
  pull_request:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync docs deps only
        run: uv sync --group docs --no-dev

      - name: Build docs (strict)
        run: uv run mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

