name: Ruff
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: # allow manual trigger
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          lfs: true
      - uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
          cache-suffix: lint
      - name: Run lint checks
        run: uv run --group dev just lint
