name: Generate Site

on:
  push:
    tags:
      - "v*"
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'pyproject.toml'
      - 'src/**'
  workflow_dispatch:  # allow manual trigger

jobs:
  build-site:
    runs-on: ubuntu-latest
    if: github.ref_name =~ '^v[0-9]+\.[0-9]+\.[0-9]+$'
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync docs deps only
        run: uv sync --group docs --no-dev

      - name: Build and deploy MkDocs site
        run: uv run mkdocs gh-deploy --force

      # - name: Build docs (strict)
      #   run: uv run mkdocs build --strict

      # - name: Upload site artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: site
      #     path: site/

